# Generated by Django 2.2.7 on 2019-11-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('pick', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Eithers',
            new_name='Question',
        ),
    ]
